SELECT P.PED_NUMERO, C.CLI_NOME, PR.PRO_DESCRICAO
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
INNER JOIN PRODUTO PR ON PR.PRO_CODIGO = I.PRO_CODIGO
ORDER BY P.PED_NUMERO;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C
LEFT JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C, PEDIDO P
WHERE C.CLI_CODIGO = P.CLI_CODIGO(+);







