SELECT *
FROM CLIENTE
ORDER BY CLI_NOME;

SELECT CLI_NOME
FROM CLIENTE
WHERE CLI_NOME LIKE '%Souza%' AND CLI_ESTADO = 'SP';

SELECT CLI_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE PED_NUMERO = 1;

SELECT C.CLI_NOME,V.VEN_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
WHERE P.PED_NUMERO = 2;

SELECT COUNT(*) AS TOTAL_PEDIDOS
FROM PEDIDO;

SELECT V.VEN_NOME, COUNT(*) AS TOTAL_PEDIDOS
FROM PEDIDO P
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
GROUP BY V.VEN_NOME, V.VEN_CODIGO
ORDER BY V.VEN_NOME;

SELECT I.ITEM_QUANTIDADE
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE P.PED_NUMERO = 1;

SELECT SUM(ITEM_QUANTIDADE) AS TOTAL_ITENS
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE P.PED_NUMERO = 1;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T
INNER JOIN CLIENTE C ON T.CLI_CODIGO = C.CLI_CODIGO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T
LEFT JOIN CLIENTE C ON C.CLI_CODIGO = T.CLI_CODIGO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T, CLIENTE C
WHERE T.CLI_CODIGO = C.CLI_CODIGO(+);

SELECT *
FROM PEDIDO
WHERE PED_DATA = TO_DATE('31/05/2026','DD/MM/YYYY');

SELECT *
FROM PEDIDO
WHERE PED_DATA = TO_DATE('31/05/2026','DD/MM/YYYY')
AND PED_PRAZO_ENTREGA > 3;

SELECT *
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
INNER JOIN PRODUTO PT ON PT.PRO_CODIGO = I.PRO_CODIGO
WHERE PRO_DESCRICAO = 'Leite Integral 1L';

SELECT P.PED_NUMERO, P.PED_DATA, C.CLI_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE C.CLI_CODIGO = 1;

SELECT COUNT(*) AS QUANTIDADE_PEDIDO
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE C.CLI_CODIGO = 2;

SELECT PRO_DESCRICAO
FROM PRODUTO
ORDER BY PRO_VALOR_UNIDADE DESC;

SELECT PRO_DESCRICAO
FROM PRODUTO
WHERE PRO_VALOR_UNIDADE = (SELECT MAX(PRO_VALOR_UNIDADE) FROM PRODUTO);

SELECT *
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE I.ITEM_QUANTIDADE > 5;

SELECT C.CLI_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
WHERE P.PED_PRAZO_ENTREGA > 15 
AND C.CLI_ESTADO IN ('RJ', 'SP');

SELECT P.PED_NUMERO, P.PED_DATA, C.CLI_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
ORDER BY P.PED_NUMERO;

SELECT P.PED_NUMERO, V.VEN_NOME, P.PED_DATA
FROM PEDIDO P
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY P.PED_NUMERO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T ON T.CLI_CODIGO = C.CLI_CODIGO
ORDER BY C.CLI_NOME;

SELECT PD.PED_NUMERO, P.PRO_DESCRICAO
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO
INNER JOIN PEDIDO PD ON PD.PED_NUMERO = I.PED_NUMERO;

SELECT P.PED_NUMERO, C.CLI_NOME, PR.PRO_DESCRICAO
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
INNER JOIN PRODUTO PR ON PR.PRO_CODIGO = I.PRO_CODIGO
ORDER BY P.PED_NUMERO;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C
LEFT JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
ORDER BY P.PED_NUMERO;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C, PEDIDO P
WHERE C.CLI_CODIGO = P.CLI_CODIGO(+)
ORDER BY P.PED_NUMERO;

SELECT P.PRO_DESCRICAO
FROM PRODUTO P
LEFT JOIN ITEM_PEDIDO I ON I.PRO_CODIGO = P.PRO_CODIGO
LEFT JOIN PEDIDO PD ON PD.PED_NUMERO = I.PED_NUMERO
ORDER BY P.PRO_DESCRICAO;

SELECT DISTINCT P.PRO_DESCRICAO
FROM PRODUTO P, ITEM_PEDIDO I, PEDIDO PD
WHERE I.PRO_CODIGO (+) = P.PRO_CODIGO
AND PD.PED_NUMERO (+) = I.PED_NUMERO
ORDER BY P.PRO_DESCRICAO;

SELECT V.VEN_NOME, P.PED_NUMERO
FROM PEDIDO P
RIGHT JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY V.VEN_NOME;

SELECT V.VEN_NOME, P.PED_NUMERO
FROM PEDIDO P, VENDEDOR V
WHERE P.VEN_CODIGO(+) = V.VEN_CODIGO
ORDER BY V.VEN_NOME;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS TOTAL_PEDIDOS
FROM PEDIDO P
RIGHT JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
GROUP BY V.VEN_CODIGO, V.VEN_NOME
ORDER BY V.VEN_NOME;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS TOTAL_PEDIDOS
FROM VENDEDOR V, PEDIDO P
WHERE V.VEN_CODIGO = P.VEN_CODIGO(+)
GROUP BY V.VEN_CODIGO, V.VEN_NOME
ORDER BY V.VEN_NOME;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM CLIENTE C
LEFT JOIN TELEFONE T ON T.CLI_CODIGO = C.CLI_CODIGO
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM CLIENTE C, TELEFONE T
WHERE C.CLI_CODIGO = T.CLI_CODIGO(+)
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C
RIGHT JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C, PEDIDO P
WHERE C.CLI_CODIGO(+) = P.CLI_CODIGO
ORDER BY C.CLI_NOME;

SELECT PD.PRO_DESCRICAO, I.ITEM_QUANTIDADE, P.PED_NUMERO
FROM PRODUTO PD
LEFT JOIN ITEM_PEDIDO I ON I.PRO_CODIGO = PD.PRO_CODIGO
LEFT JOIN PEDIDO P ON P.PED_NUMERO = I.PED_NUMERO
ORDER BY PD.PRO_DESCRICAO, P.PED_NUMERO;

SELECT PD.PRO_DESCRICAO, I.ITEM_QUANTIDADE, P.PED_NUMERO
FROM PRODUTO PD, ITEM_PEDIDO I, PEDIDO P
WHERE I.PRO_CODIGO(+) = PD.PRO_CODIGO
AND P.PED_NUMERO(+) = I.PED_NUMERO
ORDER BY PD.PRO_DESCRICAO, P.PED_NUMERO;

SELECT C.CLI_NOME, P.PED_NUMERO, PG.PAG_TIPO
FROM CLIENTE C
LEFT JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
LEFT JOIN PAGAMENTO PG ON P.PED_NUMERO = PG.PED_NUMERO
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, P.PED_NUMERO, PG.PAG_TIPO
FROM CLIENTE C, PEDIDO P, PAGAMENTO PG
WHERE C.CLI_CODIGO = P.CLI_CODIGO(+)
AND P.PED_NUMERO = PG.PED_NUMERO(+)
ORDER BY C.CLI_NOME;

SELECT V.VEN_NOME, P.PED_NUMERO
FROM VENDEDOR V
FULL JOIN PEDIDO P ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY V.VEN_NOME;

SELECT I.ITEM_QUANTIDADE, P.PRO_DESCRICAO
FROM ITEM_PEDIDO I
FULL JOIN PRODUTO P ON I.PRO_CODIGO = P.PRO_CODIGO;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C
LEFT JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE PED_NUMERO IS NULL;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C, PEDIDO P
WHERE C.CLI_CODIGO = P.CLI_CODIGO(+)
AND PED_NUMERO IS NULL;

SELECT MAX(PRO_VALOR_UNIDADE) AS PRODUTO_MAIS_CARO
FROM PRODUTO;

SELECT MIN(PRO_VALOR_UNIDADE) AS PRODUTO_MAIS_BARATO
FROM PRODUTO;

SELECT PRO_DESCRICAO, PRO_VALOR_UNIDADE
FROM PRODUTO
WHERE PRO_VALOR_UNIDADE > (SELECT AVG(PRO_VALOR_UNIDADE) FROM PRODUTO)
ORDER BY PRO_VALOR_UNIDADE;

SELECT VEN_NOME, VEN_SALARIO_FIXO
FROM VENDEDOR 
WHERE VEN_SALARIO_FIXO > (SELECT AVG(VEN_SALARIO_FIXO)FROM VENDEDOR)
ORDER BY VEN_SALARIO_FIXO;

SELECT C.CLI_NOME, COUNT(*) AS TOTAL_PEDIDOS
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
GROUP BY C.CLI_CODIGO, C.CLI_NOME
HAVING COUNT(*) = (
SELECT MAX(COUNT(*)) 
FROM PEDIDO 
GROUP BY CLI_CODIGO);

SELECT C.CLI_NOME, COUNT(P.PED_NUMERO) AS TOTAL_PEDIDOS
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
GROUP BY C.CLI_CODIGO, C.CLI_NOME
HAVING COUNT(P.PED_NUMERO) > (
SELECT AVG(COUNT(*))
FROM PEDIDO
GROUP BY CLI_CODIGO)
ORDER BY TOTAL_PEDIDOS DESC;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS QUANTIDADE_DE_PEDIDOS
FROM VENDEDOR V
INNER JOIN PEDIDO P ON P.VEN_CODIGO = V.VEN_CODIGO
GROUP BY V.VEN_NOME, V.VEN_CODIGO
HAVING COUNT(P.PED_NUMERO) > (
SELECT AVG(COUNT(*))
FROM PEDIDO
GROUP BY VEN_CODIGO)
ORDER BY QUANTIDADE_DE_PEDIDOS DESC;

SELECT DISTINCT P.PRO_DESCRICAO, P.PRO_VALOR_UNIDADE
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO
WHERE P.PRO_VALOR_UNIDADE > (
SELECT AVG(P.PRO_VALOR_UNIDADE)
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO)
ORDER BY P.PRO_VALOR_UNIDADE DESC;

SELECT C.CLI_NOME, COUNT(P.PED_NUMERO) AS PEDIDO_POR_CLIENTE
FROM CLIENTE C
LEFT JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
GROUP BY C.CLI_CODIGO, C.CLI_NOME
ORDER BY PEDIDO_POR_CLIENTE DESC;

SELECT C.CLI_NOME, COUNT(P.PED_NUMERO) AS PEDIDO_POR_CLIENTE
FROM CLIENTE C, PEDIDO P
WHERE C.CLI_CODIGO = P.CLI_CODIGO(+)
GROUP BY C.CLI_CODIGO, C.CLI_NOME
ORDER BY PEDIDO_POR_CLIENTE DESC;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS VENDAS_POR_VENDEDOR
FROM VENDEDOR V
LEFT JOIN PEDIDO P ON V.VEN_CODIGO = P.VEN_CODIGO
GROUP BY V.VEN_CODIGO, V.VEN_NOME
ORDER BY VENDAS_POR_VENDEDOR DESC;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS VENDAS_POR_VENDEDOR
FROM VENDEDOR V, PEDIDO P
WHERE V.VEN_CODIGO = P.VEN_CODIGO(+)
GROUP BY V.VEN_CODIGO, V.VEN_NOME
ORDER BY VENDAS_POR_VENDEDOR DESC;

SELECT P.PED_NUMERO, COUNT(DISTINCT I.PRO_CODIGO) AS PRODUTOS_DIFERENTES
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
GROUP BY P.PED_NUMERO
ORDER BY P.PED_NUMERO;

SELECT AVG(PRO_VALOR_UNIDADE) AS MEDIA_DOS_PRODUTOS
FROM PRODUTO;

SELECT C.CLI_NOME, COUNT(P.PED_NUMERO) AS QUANTIDADE_PEDIDOS
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
GROUP BY C.CLI_NOME, C.CLI_CODIGO
HAVING COUNT (P.PED_NUMERO) > 2
ORDER BY QUANTIDADE_PEDIDOS DESC;

SELECT V.VEN_NOME, COUNT(P.PED_NUMERO) AS QUANTIDADE_PEDIDOS
FROM VENDEDOR V
INNER JOIN PEDIDO P ON P.VEN_CODIGO = V.VEN_CODIGO
GROUP BY V.VEN_CODIGO, V.VEN_NOME
HAVING COUNT(P.PED_NUMERO) > 5
ORDER BY QUANTIDADE_PEDIDOS DESC;

SELECT P.PRO_DESCRICAO, 
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO,
(SELECT SUM(ITEM_QUANTIDADE) FROM ITEM_PEDIDO) AS TOTAL_GERAL
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO
GROUP BY P.PRO_CODIGO, P.PRO_DESCRICAO
ORDER BY TOTAL_VENDIDO DESC;

SELECT C.CLI_NOME, 
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO,
(SELECT SUM(ITEM_QUANTIDADE) FROM ITEM_PEDIDO) AS TOTAL_GERAL
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN ITEM_PEDIDO I ON P.PED_NUMERO = I.PED_NUMERO
GROUP BY C.CLI_CODIGO, C.CLI_NOME
ORDER BY TOTAL_VENDIDO DESC;

SELECT P.PRO_DESCRICAO,
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO,
(SELECT SUM(ITEM_QUANTIDADE) FROM ITEM_PEDIDO) AS TOTAL_GERAL
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO
GROUP BY P.PRO_CODIGO, P.PRO_DESCRICAO
ORDER BY TOTAL_VENDIDO DESC;

SELECT V.VEN_NOME,
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO,
(SELECT SUM(ITEM_QUANTIDADE) FROM ITEM_PEDIDO) AS TOTAL_GERAL
FROM VENDEDOR V
INNER JOIN PEDIDO P ON P.VEN_CODIGO = V.VEN_CODIGO
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
GROUP BY V.VEN_CODIGO, V.VEN_NOME
ORDER BY TOTAL_VENDIDO DESC;

SELECT NVL(C.CLI_NOME, 'TOTAL GERAL') AS CLIENTE,
NVL(V.VEN_NOME, 'SUBTOTAL') AS VENDEDOR,
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
GROUP BY ROLLUP(C.CLI_NOME, V.VEN_NOME)
ORDER BY C.CLI_NOME, V.VEN_NOME;

SELECT NVL(C.CLI_NOME, 'TOTAL GERAL') AS CLIENTE,
NVL(V.VEN_NOME, 'TOTAL GERAL') AS VENDEDOR,
SUM(I.ITEM_QUANTIDADE) AS TOTAL_VENDIDO
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
GROUP BY CUBE(C.CLI_NOME, V.VEN_NOME)
ORDER BY C.CLI_NOME, V.VEN_NOME;

CREATE VIEW VW_PRODUCTOS_VENDIDOS AS
SELECT PRO_DESCRICAO, PRO_QUANTIDADE
FROM PRODUTO;

SELECT DISTINCT C.CLI_NOME, V.VEN_NOME
FROM CLIENTE C 
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY C.CLI_NOME, V.VEN_NOME;

SELECT DISTINCT CLI_NOME, CLI_CIDADE, CLI_ESTADO
FROM CLIENTE
ORDER BY CLI_NOME;

SELECT C.CLI_NOME, V.VEN_NOME
FROM CLIENTE C 
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY C.CLI_NOME, V.VEN_NOME;

SELECT C.CLI_NOME, V.VEN_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
WHERE C.CLI_NOME LIKE '%' || V.VEN_NOME || '%'
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, V.VEN_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
WHERE C.CLI_NOME LIKE V.VEN_NOME || '%'
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, V.VEN_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
WHERE C.CLI_NOME LIKE '%' || V.VEN_NOME
ORDER BY C.CLI_NOME;

SELECT C.CLI_NOME, P.PED_NUMERO
FROM CLIENTE C
LEFT JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
WHERE P.PED_NUMERO IS NULL
ORDER BY C.CLI_NOME;

SELECT P.PRO_DESCRICAO, P.PRO_CODIGO
FROM PRODUTO P
LEFT JOIN ITEM_PEDIDO I ON I.PRO_CODIGO = P.PRO_CODIGO
WHERE I.PRO_CODIGO IS NULL
ORDER BY P.PRO_DESCRICAO;

SELECT V.VEN_NOME, V.VEN_CODIGO
FROM VENDEDOR V
LEFT JOIN PEDIDO P ON P.VEN_CODIGO = V.VEN_CODIGO
WHERE P.VEN_CODIGO IS NULL
ORDER BY V.VEN_NOME;




