SELECT *
FROM CLIENTE
ORDER BY CLI_NOME;

SELECT CLI_NOME
FROM CLIENTE
WHERE CLI_NOME LIKE '%Souza%' AND CLI_ESTADO = 'SP';

SELECT CLI_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE PED_NUMERO = 1;

SELECT C.CLI_NOME,V.VEN_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON P.CLI_CODIGO = C.CLI_CODIGO
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
WHERE P.PED_NUMERO = 2;

SELECT COUNT(*) AS TOTAL_PEDIDOS
FROM PEDIDO;

SELECT V.VEN_NOME, COUNT(*) AS TOTAL_PEDIDOS
FROM PEDIDO P
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
GROUP BY V.VEN_NOME, V.VEN_CODIGO
ORDER BY V.VEN_NOME;

SELECT I.ITEM_QUANTIDADE
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE P.PED_NUMERO = 1;

SELECT SUM(ITEM_QUANTIDADE) AS TOTAL_ITENS
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE P.PED_NUMERO = 1;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T
INNER JOIN CLIENTE C ON T.CLI_CODIGO = C.CLI_CODIGO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T
LEFT JOIN CLIENTE C ON C.CLI_CODIGO = T.CLI_CODIGO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM TELEFONE T, CLIENTE C
WHERE T.CLI_CODIGO = C.CLI_CODIGO(+);

SELECT *
FROM PEDIDO
WHERE PED_DATA = TO_DATE('31/05/2026','DD/MM/YYYY');

SELECT *
FROM PEDIDO
WHERE PED_DATA = TO_DATE('31/05/2026','DD/MM/YYYY')
AND PED_PRAZO_ENTREGA > 3;

SELECT *
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
INNER JOIN PRODUTO PT ON PT.PRO_CODIGO = I.PRO_CODIGO
WHERE PRO_DESCRICAO = 'Leite Integral 1L';

SELECT P.PED_NUMERO, P.PED_DATA, C.CLI_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE C.CLI_CODIGO = 1;

SELECT COUNT(*) AS QUANTIDADE_PEDIDO
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
WHERE C.CLI_CODIGO = 2;

SELECT PRO_DESCRICAO
FROM PRODUTO
ORDER BY PRO_VALOR_UNIDADE DESC;

SELECT PRO_DESCRICAO
FROM PRODUTO
WHERE PRO_VALOR_UNIDADE = (SELECT MAX(PRO_VALOR_UNIDADE) FROM PRODUTO);

SELECT *
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO I ON I.PED_NUMERO = P.PED_NUMERO
WHERE I.ITEM_QUANTIDADE > 5;

SELECT C.CLI_NOME
FROM CLIENTE C
INNER JOIN PEDIDO P ON P.CLI_CODIGO = C.CLI_CODIGO
WHERE P.PED_PRAZO_ENTREGA > 15 
AND C.CLI_ESTADO IN ('RJ', 'SP');

SELECT P.PED_NUMERO, P.PED_DATA, C.CLI_NOME
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.CLI_CODIGO = P.CLI_CODIGO
ORDER BY P.PED_NUMERO;

SELECT P.PED_NUMERO, V.VEN_NOME, P.PED_DATA
FROM PEDIDO P
INNER JOIN VENDEDOR V ON V.VEN_CODIGO = P.VEN_CODIGO
ORDER BY P.PED_NUMERO;

SELECT C.CLI_NOME, T.TEL_NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T ON T.CLI_CODIGO = C.CLI_CODIGO
ORDER BY C.CLI_NOME;

SELECT PD.PED_NUMERO, P.PRO_DESCRICAO
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO I ON P.PRO_CODIGO = I.PRO_CODIGO
INNER JOIN PEDIDO PD ON PD.PED_NUMERO = I.PED_NUMERO;

SELECT P.PED_NUMERO, C.CLI_NOME, PR.PRO_DESCRICAO
FROM PEDIDO P



